#!/bin/sh
mvn clean package && docker build -t Mohit Jariwala/MyFirstMicroServiceApp .
docker rm -f MyFirstMicroServiceApp 2>/dev/null || true && docker run -it --name MyFirstMicroServiceApp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name MyFirstMicroServiceApp Mohit Jariwala/MyFirstMicroServiceApp
