#!/bin/sh
#deploy="false"
deploy="true"

image=MyFirstMicroServiceApp
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t Mohit Jariwala/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push Mohit Jariwala/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag Mohit Jariwala/${image}:1.0-SNAPSHOT Mohit Jariwala/${image}:latest
        docker push Mohit Jariwala/${image}:latest
    fi
fi